version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pds
    ports: 
      - '5432:5432'
    volumes:
      - ./pds-db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_DATABASE: pds
    depends_on:
      - db
    ports:
      - '5000:5000'
        
volumes:
  pds-db: